# Generated by Django 5.0.4 on 2024-06-17 08:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="blok_users",
            field=models.ManyToManyField(
                blank=True, related_name="blocked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
