# Generated by Django 5.0.4 on 2024-06-16 07:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_last_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="last_active",
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_activity",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
