# Generated by Django 5.0.4 on 2024-06-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_blok_users"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="blok_users",
            new_name="block_users",
        ),
    ]
