# Generated by Django 5.0.4 on 2024-06-19 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_rename_blok_users_customuser_block_users"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
