# Generated by Django 5.0.4 on 2024-06-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0005_alter_customuser_groups_alter_customuser_is_active_and_more",
        ),
        ("accounts", "0007_customuser_friend_users_alter_customuser_groups_and_more"),
    ]

    operations = []
