# Generated by Django 5.0.4 on 2024-06-30 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_merge_20240630_1741"),
        (
            "accounts",
            "0010_customuser_default_language_alter_customuser_groups_and_more",
        ),
    ]

    operations = []
