# Generated by Django 5.0.4 on 2024-07-03 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0007_alter_customuser_groups_alter_customuser_is_active_and_more",
        ),
        ("accounts", "0011_merge_20240630_1841"),
    ]

    operations = []
