---
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    restart: always
    shm_size: 256mb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}

  web_prod:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  web_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - .:/app
      - ~/.gitconfig:/home/user/.gitconfig
      - ~/.ssh/:/home/user/.ssh
      - ~/.vimrc:/home/user/.vimrc
      - ~/.gnupg/:/home/user/.gnupg/
      - node_volume:/app/node_modules
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      SSH_AUTH_SOCK: /ssh-agent
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      - db

volumes:
  postgres_data:
  node_volume:
