global:
  scrape_interval: 15s
scrape_configs:
#  - job_name: 'django_app_dev'
#    metrics_path: '/prometheus/metrics'
#    static_configs:
#      - targets: ['web-dev:8000']
  - job_name: 'django_app_prod'
    metrics_path: '/prometheus/metrics'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['web-prod:8000']
