# Generated by Django 5.0.4 on 2024-06-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pingpong", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="match",
            name="game",
        ),
        migrations.RemoveField(
            model_name="match",
            name="player1",
        ),
        migrations.RemoveField(
            model_name="match",
            name="player2",
        ),
        migrations.DeleteModel(
            name="Game",
        ),
        migrations.DeleteModel(
            name="Match",
        ),
    ]
