# Generated by Django 5.0.4 on 2024-07-01 02:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pingpong", "0004_alter_game_player1_alter_game_player2"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="score_last_update",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
