# Generated by Django 5.0.4 on 2024-07-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pingpong", "0006_guestuser_tournament_tournamentresults"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TournamentResults",
            new_name="TournamentMatch",
        ),
    ]
